# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16m0WBzfeimQ47NSS9X_JhH0n0LWzVO86
"""

from pyspark.sql import SparkSession

from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Estadística").getOrCreate()

spark.stop()

spark

#EJERCICIOS

#Hallamos la media, mediana, moda y correlacion de los Electrodomesticos.
data = [("Licuadora", 300.00), ("Arrocera", 240.00), ("Batidora", 200.00), ("Microondas", 500.00), ("Refrigeradora", 1000.00), ("Aspiradora", 350.00), ("Plancha", 420.00), ("Celular", 600.00)]
columns = ["Producto", "Precio"]
variable = spark.createDataFrame(data,columns)

variable.select(mean(col("Precio")).alias("Media")).collect()[0]["Media"]

variable.select(mean(col("Precio")).alias("Media")).show()

v_mediana = variable.approxQuantile("Precio", [0.5], 0.0)

print("La mediana es", v_mediana)

v_moda = variable.groupBy("Precio").count().orderBy(col("count").desc()).first()

print("La moda es", v_moda["Precio"])



#Aplicamos la correlación
data_var = [(3,4),(4,3),(5,2),(4,1),(3,2),(2,3),(1,4),(2,3),(5,2),(4,1),(3,1),(2,2),(2,3),(2,4),(1,4)]
columns_var = ["var1","var2"]
variable_corr = spark.createDataFrame(data_var,columns_var)



correlación = variable_corr.select(corr("var1", "var2").alias("correlación")).collect()[0]["correlación"]

